{
  "kind": "discovery#restDescription",
  "protocol": "rest",
  "revision": "20220802",
  "ownerDomain": "google.com",
  "title": "Fitness API",
  "name": "fitness",
  "basePath": "/fitness/v1/users/",
  "rootUrl": "https://fitness.googleapis.com/",
  "batchPath": "batch",
  "mtlsRootUrl": "https://fitness.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "version": "v1",
  "servicePath": "fitness/v1/users/",
  "description": "The Fitness API for managing users' fitness tracking data.",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/fit/rest/v1/get-started",
  "id": "fitness:v1",
  "baseUrl": "https://fitness.googleapis.com/fitness/v1/users/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/fitness.activity.read": {
          "description": "Use Google Fit to see and store your physical activity data"
        },
        "https://www.googleapis.com/auth/fitness.body_temperature.write": {
          "description": "Add to info about your body temperature in Google Fit. I consent to Google using my body temperature information with this app."
        },
        "https://www.googleapis.com/auth/fitness.location.read": {
          "description": "See your Google Fit speed and distance data"
        },
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.read": {
          "description": "See info about your oxygen saturation in Google Fit. I consent to Google sharing my oxygen saturation information with this app."
        },
        "https://www.googleapis.com/auth/fitness.blood_pressure.write": {
          "description": "Add info about your blood pressure in Google Fit. I consent to Google using my blood pressure information with this app."
        },
        "https://www.googleapis.com/auth/fitness.body.read": {
          "description": "See info about your body measurements in Google Fit"
        },
        "https://www.googleapis.com/auth/fitness.reproductive_health.write": {
          "description": "Add info about your reproductive health in Google Fit. I consent to Google using my reproductive health information with this app."
        },
        "https://www.googleapis.com/auth/fitness.heart_rate.write": {
          "description": "Add to your heart rate data in Google Fit. I consent to Google using my heart rate information with this app."
        },
        "https://www.googleapis.com/auth/fitness.activity.write": {
          "description": "Add to your Google Fit physical activity data"
        },
        "https://www.googleapis.com/auth/fitness.nutrition.write": {
          "description": "Add to info about your nutrition in Google Fit"
        },
        "https://www.googleapis.com/auth/fitness.sleep.write": {
          "description": "Add to your sleep data in Google Fit. I consent to Google using my sleep information with this app."
        },
        "https://www.googleapis.com/auth/fitness.reproductive_health.read": {
          "description": "See info about your reproductive health in Google Fit. I consent to Google sharing my reproductive health information with this app."
        },
        "https://www.googleapis.com/auth/fitness.body.write": {
          "description": "Add info about your body measurements to Google Fit"
        },
        "https://www.googleapis.com/auth/fitness.blood_glucose.write": {
          "description": "Add info about your blood glucose to Google Fit. I consent to Google using my blood glucose information with this app."
        },
        "https://www.googleapis.com/auth/fitness.body_temperature.read": {
          "description": "See info about your body temperature in Google Fit. I consent to Google sharing my body temperature information with this app."
        },
        "https://www.googleapis.com/auth/fitness.blood_glucose.read": {
          "description": "See info about your blood glucose in Google Fit. I consent to Google sharing my blood glucose information with this app."
        },
        "https://www.googleapis.com/auth/fitness.nutrition.read": {
          "description": "See info about your nutrition in Google Fit"
        },
        "https://www.googleapis.com/auth/fitness.sleep.read": {
          "description": "See your sleep data in Google Fit. I consent to Google sharing my sleep information with this app."
        },
        "https://www.googleapis.com/auth/fitness.location.write": {
          "description": "Add to your Google Fit location data"
        },
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write": {
          "description": "Add info about your oxygen saturation in Google Fit. I consent to Google using my oxygen saturation information with this app."
        },
        "https://www.googleapis.com/auth/fitness.heart_rate.read": {
          "description": "See your heart rate data in Google Fit. I consent to Google sharing my heart rate information with this app."
        },
        "https://www.googleapis.com/auth/fitness.blood_pressure.read": {
          "description": "See info about your blood pressure in Google Fit. I consent to Google sharing my blood pressure information with this app."
        }
      }
    }
  },
  "resources": {
    "users": {
      "resources": {
        "dataSources": {
          "methods": {
            "update": {
              "httpMethod": "PUT",
              "id": "fitness.users.dataSources.update",
              "path": "{userId}/dataSources/{dataSourceId}",
              "description": "Updates the specified data source. The dataStreamId, dataType, type, dataStreamName, and device properties with the exception of version, cannot be modified. Data sources are identified by their dataStreamId.",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.heart_rate.write",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write",
                "https://www.googleapis.com/auth/fitness.sleep.write"
              ],
              "flatPath": "{userId}/dataSources/{dataSourceId}"
            },
            "create": {
              "description": "Creates a new data source that is unique across all data sources belonging to this user. A data source is a unique source of sensor data. Data sources can expose raw data coming from hardware sensors on local or companion devices. They can also expose derived data, created by transforming or merging other data sources. Multiple data sources can exist for the same data type. Every data point in every dataset inserted into or read from the Fitness API has an associate[...]",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.heart_rate.write",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write",
                "https://www.googleapis.com/auth/fitness.sleep.write"
              ],
              "path": "{userId}/dataSources",
              "flatPath": "{userId}/dataSources",
              "id": "fitness.users.dataSources.create"
            },
            "get": {
              "id": "fitness.users.dataSources.get",
              "flatPath": "{userId}/dataSources/{dataSourceId}",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.read",
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.read",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.heart_rate.read",
                "https://www.googleapis.com/auth/fitness.heart_rate.write",
                "https://www.googleapis.com/auth/fitness.location.read",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.read",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write",
                "https://www.googleapis.com/auth/fitness.sleep.read",
                "https://www.googleapis.com/auth/fitness.sleep.write"
              ],
              "description": "Returns the specified data source.",
              "path": "{userId}/dataSources/{dataSourceId}",
              "httpMethod": "GET"
            },
            "list": {
              "description": "Lists all data sources that are visible to the developer, using the OAuth scopes provided. The list is not exhaustive; the user may have private data sources that are only visible to other developers, or calls using other scopes.",
              "flatPath": "{userId}/dataSources",
              "path": "{userId}/dataSources",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.read",
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.read",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.heart_rate.read",
                "https://www.googleapis.com/auth/fitness.heart_rate.write",
                "https://www.googleapis.com/auth/fitness.location.read",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.read",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write",
                "https://www.googleapis.com/auth/fitness.sleep.read",
                "https://www.googleapis.com/auth/fitness.sleep.write"
              ],
              "id": "fitness.users.dataSources.list"
            },
            "delete": {
              "id": "fitness.users.dataSources.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.heart_rate.write",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write",
                "https://www.googleapis.com/auth/fitness.sleep.write"
              ],
              "description": "Deletes the specified data source. The request will fail if the data source contains any data points.",
              "flatPath": "{userId}/dataSources/{dataSourceId}",
              "path": "{userId}/dataSources/{dataSourceId}"
            }
          },
          "resources": {
            "datasets": {
              "methods": {
                "get": {
                  "flatPath": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/fitness.activity.read",
                    "https://www.googleapis.com/auth/fitness.activity.write",
                    "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                    "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                    "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                    "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                    "https://www.googleapis.com/auth/fitness.body.read",
                    "https://www.googleapis.com/auth/fitness.body.write",
                    "https://www.googleapis.com/auth/fitness.body_temperature.read",
                    "https://www.googleapis.com/auth/fitness.body_temperature.write",
                    "https://www.googleapis.com/auth/fitness.heart_rate.read",
                    "https://www.googleapis.com/auth/fitness.heart_rate.write",
                    "https://www.googleapis.com/auth/fitness.location.read",
                    "https://www.googleapis.com/auth/fitness.location.write",
                    "https://www.googleapis.com/auth/fitness.nutrition.read",
                    "https://www.googleapis.com/auth/fitness.nutrition.write",
                    "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                    "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                    "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                    "https://www.googleapis.com/auth/fitness.reproductive_health.write",
                    "https://www.googleapis.com/auth/fitness.sleep.read",
                    "https://www.googleapis.com/auth/fitness.sleep.write"
                  ],
                  "id": "fitness.users.dataSources.datasets.get",
                  "description": "Returns a dataset containing all data points whose start and end times overlap with the specified range of the dataset minimum start time and maximum end time. Specifically, any data point whose start time is less than or equal to the dataset end time and whose end time is greater than or equal to the dataset start time.",
                  "httpMethod": "GET",
                  "path": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}"
                },
                "patch": {
                  "description": "Adds data points to a dataset. The dataset need not be previously created. All points within the given dataset will be returned with subsquent calls to retrieve this dataset. Data points can belong to more than one dataset. This method does not use patch semantics: the data points provided are merely inserted, with no existing data replaced.",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/fitness.activity.write",
                    "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                    "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                    "https://www.googleapis.com/auth/fitness.body.write",
                    "https://www.googleapis.com/auth/fitness.body_temperature.write",
                    "https://www.googleapis.com/auth/fitness.heart_rate.write",
                    "https://www.googleapis.com/auth/fitness.location.write",
                    "https://www.googleapis.com/auth/fitness.nutrition.write",
                    "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                    "https://www.googleapis.com/auth/fitness.reproductive_health.write",
                    "https://www.googleapis.com/auth/fitness.sleep.write"
                  ],
                  "path": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                  "id": "fitness.users.dataSources.datasets.patch",
                  "flatPath": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}"
                },
                "delete": {
                  "flatPath": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                  "path": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/fitness.activity.write",
                    "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                    "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                    "https://www.googleapis.com/auth/fitness.body.write",
                    "https://www.googleapis.com/auth/fitness.body_temperature.write",
                    "https://www.googleapis.com/auth/fitness.heart_rate.write",
                    "https://www.googleapis.com/auth/fitness.location.write",
                    "https://www.googleapis.com/auth/fitness.nutrition.write",
                    "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                    "https://www.googleapis.com/auth/fitness.reproductive_health.write",
                    "https://www.googleapis.com/auth/fitness.sleep.write"
                  ],
                  "id": "fitness.users.dataSources.datasets.delete",
                  "description": "Performs an inclusive delete of all data points whose start and end times have any overlap with the time range specified by the dataset ID. For most data types, the entire data point will be deleted. For data types where the time span represents a consistent value (such as com.google.activity.segment), and a data point straddles either end point of the dataset, only the overlapping portion of the data point will be deleted.",
                  "httpMethod": "DELETE"
                }
              }
            },
            "dataPointChanges": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/fitness.activity.read",
                    "https://www.googleapis.com/auth/fitness.activity.write",
                    "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                    "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                    "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                    "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                    "https://www.googleapis.com/auth/fitness.body.read",
                    "https://www.googleapis.com/auth/fitness.body.write",
                    "https://www.googleapis.com/auth/fitness.body_temperature.read",
                    "https://www.googleapis.com/auth/fitness.body_temperature.write",
                    "https://www.googleapis.com/auth/fitness.heart_rate.read",
                    "https://www.googleapis.com/auth/fitness.heart_rate.write",
                    "https://www.googleapis.com/auth/fitness.location.read",
                    "https://www.googleapis.com/auth/fitness.location.write",
                    "https://www.googleapis.com/auth/fitness.nutrition.read",
                    "https://www.googleapis.com/auth/fitness.nutrition.write",
                    "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                    "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                    "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                    "https://www.googleapis.com/auth/fitness.reproductive_health.write",
                    "https://www.googleapis.com/auth/fitness.sleep.read",
                    "https://www.googleapis.com/auth/fitness.sleep.write"
                  ],
                  "id": "fitness.users.dataSources.dataPointChanges.list",
                  "path": "{userId}/dataSources/{dataSourceId}/dataPointChanges",
                  "description": "Queries for user's data point changes for a particular data source.",
                  "httpMethod": "GET",
                  "flatPath": "{userId}/dataSources/{dataSourceId}/dataPointChanges"
                }
              }
            }
          }
        },
        "sessions": {
          "methods": {
            "list": {
              "path": "{userId}/sessions",
              "id": "fitness.users.sessions.list",
              "flatPath": "{userId}/sessions",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.read",
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.read",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.heart_rate.read",
                "https://www.googleapis.com/auth/fitness.heart_rate.write",
                "https://www.googleapis.com/auth/fitness.location.read",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.read",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write",
                "https://www.googleapis.com/auth/fitness.sleep.read",
                "https://www.googleapis.com/auth/fitness.sleep.write"
              ],
              "httpMethod": "GET",
              "description": "Lists sessions previously created."
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.sleep.write"
              ],
              "flatPath": "{userId}/sessions/{sessionId}",
              "id": "fitness.users.sessions.delete",
              "description": "Deletes a session specified by the given session ID.",
              "path": "{userId}/sessions/{sessionId}"
            },
            "update": {
              "flatPath": "{userId}/sessions/{sessionId}",
              "id": "fitness.users.sessions.update",
              "description": "Updates or insert a given session.",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.sleep.write"
              ],
              "path": "{userId}/sessions/{sessionId}",
              "httpMethod": "PUT"
            }
          }
        },
        "dataset": {
          "methods": {
            "aggregate": {
              "description": "Aggregates data of a certain type or stream into buckets divided by a given type of boundary. Multiple data sets of multiple types and from multiple sources can be aggregated into exactly one bucket type per request.",
              "id": "fitness.users.dataset.aggregate",
              "path": "{userId}/dataset:aggregate",
              "flatPath": "{userId}/dataset:aggregate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/fitness.activity.read",
                "https://www.googleapis.com/auth/fitness.activity.write",
                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                "https://www.googleapis.com/auth/fitness.body.read",
                "https://www.googleapis.com/auth/fitness.body.write",
                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                "https://www.googleapis.com/auth/fitness.heart_rate.read",
                "https://www.googleapis.com/auth/fitness.heart_rate.write",
                "https://www.googleapis.com/auth/fitness.location.read",
                "https://www.googleapis.com/auth/fitness.location.write",
                "https://www.googleapis.com/auth/fitness.nutrition.read",
                "https://www.googleapis.com/auth/fitness.nutrition.write",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                "https://www.googleapis.com/auth/fitness.reproductive_health.write",
                "https://www.googleapis.com/auth/fitness.sleep.read",
                "https://www.googleapis.com/auth/fitness.sleep.write"
              ]
            }
          }
        }
      }
    }
  }
}
