{
  "batchPath": "batch",
  "revision": "20220726",
  "baseUrl": "https://games.googleapis.com/",
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "description": "The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "rootUrl": "https://games.googleapis.com/",
  "id": "games:v1",
  "canonicalName": "Games",
  "resources": {
    "stats": {
      "methods": {
        "get": {
          "id": "games.stats.get",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/stats",
          "httpMethod": "GET",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "path": "games/v1/stats"
        }
      }
    },
    "scores": {
      "methods": {
        "list": {
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "id": "games.scores.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "id": "games.scores.get",
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "listWindow": {
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "id": "games.scores.listWindow"
        },
        "submit": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "id": "games.scores.submit",
          "description": "Submits a score to the specified leaderboard.",
          "httpMethod": "POST"
        },
        "submitMultiple": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Submits multiple scores to leaderboards.",
          "flatPath": "games/v1/leaderboards/scores",
          "httpMethod": "POST",
          "path": "games/v1/leaderboards/scores",
          "id": "games.scores.submitMultiple"
        }
      }
    },
    "players": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}",
          "id": "games.players.get",
          "flatPath": "games/v1/players/{playerId}",
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`."
        },
        "list": {
          "description": "Get the collection of players for the currently authenticated user.",
          "httpMethod": "GET",
          "path": "games/v1/players/me/players/{collection}",
          "flatPath": "games/v1/players/me/players/{collection}",
          "id": "games.players.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "getScopedPlayerIds": {
          "flatPath": "games/v1/players/me/scopedIds",
          "description": "Retrieves scoped player identifiers for currently authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.players.getScopedPlayerIds",
          "httpMethod": "GET",
          "path": "games/v1/players/me/scopedIds"
        }
      }
    },
    "achievements": {
      "methods": {
        "list": {
          "path": "games/v1/players/{playerId}/achievements",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "flatPath": "games/v1/players/{playerId}/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.list",
          "httpMethod": "GET"
        },
        "updateMultiple": {
          "description": "Updates multiple achievements for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/updateMultiple",
          "flatPath": "games/v1/achievements/updateMultiple",
          "id": "games.achievements.updateMultiple",
          "httpMethod": "POST"
        },
        "reveal": {
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.reveal",
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "httpMethod": "POST"
        },
        "increment": {
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/increment",
          "id": "games.achievements.increment",
          "httpMethod": "POST"
        },
        "unlock": {
          "description": "Unlocks this achievement for the currently authenticated player.",
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/{achievementId}/unlock",
          "id": "games.achievements.unlock"
        },
        "setStepsAtLeast": {
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "id": "games.achievements.setStepsAtLeast",
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "flatPath": "games/v1/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievementDefinitions.list",
          "httpMethod": "GET",
          "path": "games/v1/achievements",
          "description": "Lists all the achievement definitions for your application."
        }
      }
    },
    "snapshots": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "path": "games/v1/players/{playerId}/snapshots",
          "id": "games.snapshots.list"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "id": "games.snapshots.get",
          "path": "games/v1/snapshots/{snapshotId}"
        }
      }
    },
    "applications": {
      "methods": {
        "verify": {
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "path": "games/v1/applications/{applicationId}/verify",
          "id": "games.applications.verify",
          "httpMethod": "GET",
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "getEndPoint": {
          "id": "games.applications.getEndPoint",
          "httpMethod": "POST",
          "path": "games/v1/applications/getEndPoint",
          "flatPath": "games/v1/applications/getEndPoint",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Returns a URL for the requested end point type."
        },
        "get": {
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
          "id": "games.applications.get",
          "flatPath": "games/v1/applications/{applicationId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/applications/{applicationId}"
        },
        "played": {
          "path": "games/v1/applications/played",
          "httpMethod": "POST",
          "id": "games.applications.played",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "flatPath": "games/v1/applications/played",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "flatPath": "games/v1/revisions/check",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.revisions.check",
          "httpMethod": "GET",
          "path": "games/v1/revisions/check",
          "description": "Checks whether the games client is out of date."
        }
      }
    },
    "events": {
      "methods": {
        "listDefinitions": {
          "flatPath": "games/v1/eventDefinitions",
          "path": "games/v1/eventDefinitions",
          "description": "Returns a list of the event definitions in this application.",
          "httpMethod": "GET",
          "id": "games.events.listDefinitions",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "record": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/events",
          "httpMethod": "POST",
          "id": "games.events.record",
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "path": "games/v1/events"
        },
        "listByPlayer": {
          "id": "games.events.listByPlayer",
          "path": "games/v1/events",
          "httpMethod": "GET",
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/events"
        }
      }
    },
    "metagame": {
      "methods": {
        "listCategoriesByPlayer": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "httpMethod": "GET",
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "id": "games.metagame.listCategoriesByPlayer"
        },
        "getMetagameConfig": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/metagameConfig",
          "path": "games/v1/metagameConfig",
          "httpMethod": "GET",
          "id": "games.metagame.getMetagameConfig",
          "description": "Return the metagame configuration data for the calling application."
        }
      }
    },
    "leaderboards": {
      "methods": {
        "get": {
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.leaderboards.get",
          "path": "games/v1/leaderboards/{leaderboardId}"
        },
        "list": {
          "path": "games/v1/leaderboards",
          "httpMethod": "GET",
          "id": "games.leaderboards.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists all the leaderboard metadata for your application.",
          "flatPath": "games/v1/leaderboards"
        }
      }
    }
  },
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "basePath": "",
  "name": "games",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        }
      }
    }
  },
  "version": "v1",
  "servicePath": "",
  "documentationLink": "https://developers.google.com/games/",
  "protocol": "rest",
  "ownerName": "Google",
  "title": "Google Play Game Services"
}
