{
  "documentationLink": "https://developers.google.com/tasks/",
  "batchPath": "batch",
  "protocol": "rest",
  "rootUrl": "https://tasks.googleapis.com/",
  "version": "v1",
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "revision": "20220802",
  "name": "tasks",
  "canonicalName": "Tasks",
  "ownerDomain": "google.com",
  "id": "tasks:v1",
  "description": "The Google Tasks API lets you manage your tasks and task lists.",
  "servicePath": "",
  "baseUrl": "https://tasks.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "basePath": "",
  "resources": {
    "tasks": {
      "methods": {
        "clear": {
          "description": "Clears all completed tasks from the specified task list. The affected tasks will be marked as 'hidden' and no longer be returned by default when retrieving all tasks for a task list.",
          "flatPath": "tasks/v1/lists/{tasklist}/clear",
          "httpMethod": "POST",
          "id": "tasks.tasks.clear",
          "path": "tasks/v1/lists/{tasklist}/clear",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        },
        "patch": {
          "id": "tasks.tasks.patch",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "httpMethod": "PATCH",
          "description": "Updates the specified task. This method supports patch semantics.",
          "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "tasks/v1/lists/{tasklist}/tasks",
          "description": "Returns all tasks in the specified task list.",
          "id": "tasks.tasks.list",
          "scopes": [
            "https://www.googleapis.com/auth/tasks",
            "https://www.googleapis.com/auth/tasks.readonly"
          ],
          "path": "tasks/v1/lists/{tasklist}/tasks"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates the specified task.",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "id": "tasks.tasks.update",
          "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "path": "tasks/v1/lists/{tasklist}/tasks/{task}"
        },
        "move": {
          "id": "tasks.tasks.move",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "path": "tasks/v1/lists/{tasklist}/tasks/{task}/move",
          "description": "Moves the specified task to another position in the task list. This can include putting it as a child task under a new parent and/or move it to a different position among its sibling tasks.",
          "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}/move"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/tasks",
            "https://www.googleapis.com/auth/tasks.readonly"
          ],
          "id": "tasks.tasks.get",
          "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "httpMethod": "GET",
          "description": "Returns the specified task."
        },
        "delete": {
          "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "description": "Deletes the specified task from the task list.",
          "id": "tasks.tasks.delete",
          "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "httpMethod": "DELETE"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "flatPath": "tasks/v1/lists/{tasklist}/tasks",
          "path": "tasks/v1/lists/{tasklist}/tasks",
          "id": "tasks.tasks.insert",
          "description": "Creates a new task on the specified task list.",
          "httpMethod": "POST"
        }
      }
    },
    "tasklists": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "flatPath": "tasks/v1/users/@me/lists/{tasklist}",
          "path": "tasks/v1/users/@me/lists/{tasklist}",
          "description": "Updates the authenticated user's specified task list.",
          "id": "tasks.tasklists.update"
        },
        "patch": {
          "description": "Updates the authenticated user's specified task list. This method supports patch semantics.",
          "path": "tasks/v1/users/@me/lists/{tasklist}",
          "flatPath": "tasks/v1/users/@me/lists/{tasklist}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "id": "tasks.tasklists.patch"
        },
        "get": {
          "path": "tasks/v1/users/@me/lists/{tasklist}",
          "id": "tasks.tasklists.get",
          "flatPath": "tasks/v1/users/@me/lists/{tasklist}",
          "description": "Returns the authenticated user's specified task list.",
          "scopes": [
            "https://www.googleapis.com/auth/tasks",
            "https://www.googleapis.com/auth/tasks.readonly"
          ],
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "tasks/v1/users/@me/lists",
          "description": "Creates a new task list and adds it to the authenticated user's task lists.",
          "httpMethod": "POST",
          "path": "tasks/v1/users/@me/lists",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "id": "tasks.tasklists.insert"
        },
        "list": {
          "id": "tasks.tasklists.list",
          "httpMethod": "GET",
          "path": "tasks/v1/users/@me/lists",
          "flatPath": "tasks/v1/users/@me/lists",
          "scopes": [
            "https://www.googleapis.com/auth/tasks",
            "https://www.googleapis.com/auth/tasks.readonly"
          ],
          "description": "Returns all the authenticated user's task lists."
        },
        "delete": {
          "path": "tasks/v1/users/@me/lists/{tasklist}",
          "httpMethod": "DELETE",
          "flatPath": "tasks/v1/users/@me/lists/{tasklist}",
          "description": "Deletes the authenticated user's specified task list.",
          "id": "tasks.tasklists.delete",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/tasks.readonly": {
          "description": "View your tasks"
        },
        "https://www.googleapis.com/auth/tasks": {
          "description": "Create, edit, organize, and delete all your tasks"
        }
      }
    }
  },
  "title": "Tasks API",
  "ownerName": "Google",
  "mtlsRootUrl": "https://tasks.mtls.googleapis.com/"
}
