{
  "id": "vault:v1",
  "ownerDomain": "google.com",
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "resources": {
    "matters": {
      "methods": {
        "addPermissions": {
          "path": "v1/matters/{matterId}:addPermissions",
          "description": "Adds an account as a matter collaborator.",
          "id": "vault.matters.addPermissions",
          "flatPath": "v1/matters/{matterId}:addPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Lists matters the requestor has access to.",
          "path": "v1/matters",
          "id": "vault.matters.list",
          "flatPath": "v1/matters",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "create": {
          "path": "v1/matters",
          "description": "Creates a matter with the given name and description. The initial state is open, and the owner is the method caller. Returns the created matter with default view.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters",
          "id": "vault.matters.create"
        },
        "close": {
          "httpMethod": "POST",
          "description": "Closes the specified matter. Returns the matter with updated state.",
          "flatPath": "v1/matters/{matterId}:close",
          "id": "vault.matters.close",
          "path": "v1/matters/{matterId}:close",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "undelete": {
          "id": "vault.matters.undelete",
          "path": "v1/matters/{matterId}:undelete",
          "description": "Undeletes the specified matter. Returns the matter with updated state.",
          "flatPath": "v1/matters/{matterId}:undelete",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "httpMethod": "POST"
        },
        "update": {
          "flatPath": "v1/matters/{matterId}",
          "id": "vault.matters.update",
          "description": "Updates the specified matter. This updates only the name and description of the matter, identified by matter ID. Changes to any other fields are ignored. Returns the default view of the matter.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters/{matterId}",
          "httpMethod": "PUT"
        },
        "removePermissions": {
          "path": "v1/matters/{matterId}:removePermissions",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:removePermissions",
          "id": "vault.matters.removePermissions",
          "description": "Removes an account as a matter collaborator."
        },
        "count": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:count",
          "description": "Counts the accounts processed by the specified query.",
          "httpMethod": "POST",
          "id": "vault.matters.count",
          "path": "v1/matters/{matterId}:count"
        },
        "get": {
          "description": "Gets the specified matter.",
          "path": "v1/matters/{matterId}",
          "id": "vault.matters.get",
          "httpMethod": "GET",
          "flatPath": "v1/matters/{matterId}",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "delete": {
          "path": "v1/matters/{matterId}",
          "httpMethod": "DELETE",
          "description": "Deletes the specified matter. Returns the matter with updated state.",
          "flatPath": "v1/matters/{matterId}",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.delete"
        },
        "reopen": {
          "id": "vault.matters.reopen",
          "description": "Reopens the specified matter. Returns the matter with updated state.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:reopen",
          "path": "v1/matters/{matterId}:reopen"
        }
      },
      "resources": {
        "holds": {
          "methods": {
            "get": {
              "description": "Gets the specified hold.",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "id": "vault.matters.holds.get",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "GET"
            },
            "update": {
              "description": "Updates the scope (organizational unit or accounts) and query parameters of a hold. You cannot add accounts to a hold that covers an organizational unit, nor can you add organizational units to a hold that covers individual accounts. If you try, the unsupported values are ignored.",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "id": "vault.matters.holds.update"
            },
            "list": {
              "httpMethod": "GET",
              "id": "vault.matters.holds.list",
              "description": "Lists the holds in a matter.",
              "path": "v1/matters/{matterId}/holds",
              "flatPath": "v1/matters/{matterId}/holds",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "create": {
              "description": "Creates a hold in the specified matter.",
              "flatPath": "v1/matters/{matterId}/holds",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "httpMethod": "POST",
              "id": "vault.matters.holds.create",
              "path": "v1/matters/{matterId}/holds"
            },
            "delete": {
              "id": "vault.matters.holds.delete",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "DELETE",
              "description": "Removes the specified hold and releases the accounts or organizational unit covered by the hold. If the data is not preserved by another hold or retention rule, it might be purged.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}"
            },
            "addHeldAccounts": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "description": "Adds accounts to a hold. Returns a list of accounts that have been successfully added. Accounts can be added only to an existing account-based hold.",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "id": "vault.matters.holds.addHeldAccounts",
              "httpMethod": "POST"
            },
            "removeHeldAccounts": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "id": "vault.matters.holds.removeHeldAccounts",
              "description": "Removes the specified accounts from a hold. Returns a list of statuses in the same order as the request.",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts"
            }
          },
          "resources": {
            "accounts": {
              "methods": {
                "delete": {
                  "description": "Removes an account from a hold.",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "id": "vault.matters.holds.accounts.delete",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "description": "Adds an account to a hold. Accounts can be added only to a hold that does not have an organizational unit set. If you try to add an account to an organizational unit-based hold, an error is returned.",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "id": "vault.matters.holds.accounts.create",
                  "httpMethod": "POST",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts"
                },
                "list": {
                  "description": "Lists the accounts covered by a hold. This can list only individually-specified accounts covered by the hold. If the hold covers an organizational unit, use the [Admin SDK](https://developers.google.com/admin-sdk/). to list the members of the organizational unit on hold.",
                  "id": "vault.matters.holds.accounts.list",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery",
                    "https://www.googleapis.com/auth/ediscovery.readonly"
                  ],
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "savedQueries": {
          "methods": {
            "get": {
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "id": "vault.matters.savedQueries.get",
              "httpMethod": "GET",
              "description": "Retrieves the specified saved query.",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}"
            },
            "create": {
              "description": "Creates a saved query.",
              "id": "vault.matters.savedQueries.create",
              "httpMethod": "POST",
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "path": "v1/matters/{matterId}/savedQueries",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "delete": {
              "id": "vault.matters.savedQueries.delete",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "description": "Deletes the specified saved query.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "list": {
              "path": "v1/matters/{matterId}/savedQueries",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "httpMethod": "GET",
              "id": "vault.matters.savedQueries.list",
              "description": "Lists the saved queries in a matter.",
              "flatPath": "v1/matters/{matterId}/savedQueries"
            }
          }
        },
        "exports": {
          "methods": {
            "create": {
              "id": "vault.matters.exports.create",
              "httpMethod": "POST",
              "path": "v1/matters/{matterId}/exports",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "description": "Creates an export.",
              "flatPath": "v1/matters/{matterId}/exports"
            },
            "list": {
              "path": "v1/matters/{matterId}/exports",
              "id": "vault.matters.exports.list",
              "flatPath": "v1/matters/{matterId}/exports",
              "description": "Lists details about the exports in the specified matter.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "description": "Gets an export.",
              "id": "vault.matters.exports.get",
              "httpMethod": "GET",
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "description": "Deletes an export.",
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "httpMethod": "DELETE",
              "id": "vault.matters.exports.delete",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}"
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "cancel": {
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "path": "v1/{+name}:cancel",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "id": "vault.operations.cancel",
          "httpMethod": "POST"
        },
        "list": {
          "id": "vault.operations.list",
          "path": "v1/{+name}",
          "flatPath": "v1/operations",
          "httpMethod": "GET",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `\"/v1/{name=users/*}/operations\"` to their service configuration. For backwards compatibility, the default name includes the operatio[...]"
        },
        "get": {
          "flatPath": "v1/operations/{operationsId}",
          "path": "v1/{+name}",
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "id": "vault.operations.get"
        },
        "delete": {
          "path": "v1/{+name}",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "id": "vault.operations.delete",
          "httpMethod": "DELETE",
          "flatPath": "v1/operations/{operationsId}"
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery": {
          "description": "Manage your eDiscovery data"
        },
        "https://www.googleapis.com/auth/ediscovery.readonly": {
          "description": "View your eDiscovery data"
        }
      }
    }
  },
  "servicePath": "",
  "rootUrl": "https://vault.googleapis.com/",
  "name": "vault",
  "description": "Retention and eDiscovery for Google Workspace. To work with Vault resources, the account must have the [required Vault privileges](https://support.google.com/vault/answer/2799699) and access to the matter. To access a matter, the account must have created the matter, have the matter shared with them, or have the **View All Matters** privilege. For example, to download an export, an account needs the **Manage Exports** privilege and the matter shared with them. ",
  "version_module": true,
  "mtlsRootUrl": "https://vault.mtls.googleapis.com/",
  "basePath": "",
  "revision": "20220728",
  "baseUrl": "https://vault.googleapis.com/",
  "ownerName": "Google",
  "protocol": "rest",
  "documentationLink": "https://developers.google.com/vault",
  "version": "v1",
  "title": "Google Vault API",
  "canonicalName": "Vault",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true
}
