name: Lint

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lua-check:
    name: Lua Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    if: (github.actor != 'dependabot[bot]')

    steps:
    - name: Checkout source code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

    # Optional step to run on only changed files
    - name: Get changed files
      id: changed-files
      uses: Kong/changed-files@cd69b79ca4e2a1198064c5e6564cce68920df311 # main
      with:
        files: |
          **.lua

    - name: Lua Check
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: Kong/public-shared-actions/code-check-actions/lua-lint@916a6f6221b7eab6f5ae53d061274d588c965ae6 # 5.0.2
      with:
        additional_args: '--no-default-config --config .luacheckrc'
        files: ${{ steps.changed-files.outputs.all_changed_files }}
