name: Test

on: [push, pull_request]

jobs:
  tests:
    name: Busted Tests

    strategy:
      matrix:
        openresty_version:
          - 1.17.8.2
          - 1.19.9.1

    runs-on: ubuntu-latest
    container:
      image: openresty/openresty:${{ matrix.openresty_version }}-alpine-fat
      # --init runs tinit as PID 1 and prevents the 'WARNING: killing the child process' spam from the test suite
      options: --init

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        apk add --no-cache wget tar make gcc musl-dev openssl-dev curl
        wget https://github.com/libexpat/libexpat/releases/download/R_2_7_0/expat-2.7.0.tar.gz && tar zxvf expat-2.7.0.tar.gz
        cd expat-2.7.0 && ./configure && make && make install
        wget https://luarocks.github.io/luarocks/releases/luarocks-3.12.2.tar.gz
        tar zxvf luarocks-3.12.2.tar.gz
        cd luarocks-3.12.2
        ./configure   --lua-version=5.1   --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1   --with-lua-lib=/usr/local/openresty/luajit/lib
        make
        make install
        export PATH=/usr/local/bin:$PATH
        luarocks install lua-resty-jwt
        luarocks install lua-resty-aws
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache
        key: ${{ runner.os }}-${{ matrix.openresty_version }}-cache

    - name: Install Busted
      run: |
        luarocks install busted

    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        busted
